
#type: args

train:
  epochs: 100
  batch_size: 64
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8


diffusion:
  layers: 1 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.001
  beta_end: 0.5
  num_steps: 1
  schedule: "quad"
  is_linear: False

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
